[package]
name = "ugit"
description = "A wrapper around Git that better matches your workflow. :3"
version = "0.0.1"
edition = "2021"
authors = ["Lucas Bob <lucas@pixelized.studio>"]

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
